const properties=[
{id:1,name:'白金台 パークレジデンス 603号室',area:'港区',address:'東京都港区白金台',type:'区分マンション',price:'1億2,800万円',status:'オークション中',time:'残り18時間42分',size:'専有 72.18㎡',built:'2018年3月',prefecture:'東京都',line:'都営三田線',station:'白金台駅',walk:4,landArea:0,earthquake:'新耐震',offers:12,img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80'},
{id:2,name:'渋谷区代官山町 売地',area:'渋谷区',address:'東京都渋谷区代官山町',type:'土地',price:'9,480万円',status:'入札予定',time:'開始まで12日',size:'土地 82.44㎡',built:'—',prefecture:'東京都',line:'東急東横線',station:'代官山駅',walk:7,landArea:82.44,earthquake:'対象外',offers:8,img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80'},
{id:3,name:'世田谷区深沢 戸建て',area:'世田谷区',address:'東京都世田谷区深沢',type:'戸建て',price:'7,980万円',status:'入札予定',time:'オファー受付中',size:'建物 104.26㎡',built:'2021年6月',prefecture:'東京都',line:'東急大井町線',station:'尾山台駅',walk:14,landArea:96.18,earthquake:'新耐震',offers:5,img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80'},
{id:4,name:'目黒区中央町 一棟アパート',area:'目黒区',address:'東京都目黒区中央町',type:'1棟アパート',price:'1億4,500万円',status:'オークション中',time:'残り2日6時間',size:'建物 186.30㎡',built:'1979年8月',prefecture:'東京都',line:'東急東横線',station:'学芸大学駅',walk:11,landArea:102.60,earthquake:'旧耐震',offers:9,img:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=80'},
{id:5,name:'吉祥寺北町 売地',area:'武蔵野市',address:'東京都武蔵野市吉祥寺北町',type:'土地',price:'6,250万円',status:'終了',time:'受付終了',size:'土地 116.82㎡',built:'—',prefecture:'東京都',line:'JR中央線',station:'吉祥寺駅',walk:18,landArea:116.82,earthquake:'対象外',offers:14,img:'https://images.unsplash.com/photo-1523413651479-597eb2da0ad6?auto=format&fit=crop&w=900&q=80'},
{id:6,name:'文京区小石川 リノベ戸建て',area:'文京区',address:'東京都文京区小石川',type:'戸建て',price:'8,760万円',status:'オークション中',time:'残り1日4時間',size:'建物 91.35㎡',built:'1994年5月',prefecture:'東京都',line:'東京メトロ丸ノ内線',station:'茗荷谷駅',walk:8,landArea:68.20,earthquake:'新耐震',offers:11,img:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80'},
{id:7,name:'江東区豊洲 ベイタワー 1208号室',area:'江東区',address:'東京都江東区豊洲',type:'区分マンション',price:'7,350万円',status:'入札予定',time:'開始まで5日',size:'専有 66.40㎡',built:'2015年10月',prefecture:'東京都',line:'東京メトロ有楽町線',station:'豊洲駅',walk:5,landArea:0,earthquake:'新耐震',offers:7,img:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80'},
{id:8,name:'練馬区石神井町 売地',area:'練馬区',address:'東京都練馬区石神井町',type:'土地',price:'5,180万円',status:'終了',time:'受付終了',size:'土地 104.10㎡',built:'—',prefecture:'東京都',line:'西武池袋線',station:'石神井公園駅',walk:9,landArea:104.10,earthquake:'対象外',offers:10,img:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80'},
{id:9,name:'三鷹市下連雀 戸建て',area:'三鷹市',address:'東京都三鷹市下連雀',type:'戸建て',price:'6,680万円',status:'入札予定',time:'オファー受付中',size:'建物 98.74㎡',built:'2010年4月',prefecture:'東京都',line:'JR中央線',station:'三鷹駅',walk:13,landArea:112.30,earthquake:'新耐震',offers:6,img:'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=900&q=80'},
{id:10,name:'立川市曙町 レジデンス 502号室',area:'立川市',address:'東京都立川市曙町',type:'区分マンション',price:'4,280万円',status:'オークション中',time:'残り3日2時間',size:'専有 64.08㎡',built:'2008年1月',prefecture:'東京都',line:'JR中央線',station:'立川駅',walk:6,landArea:0,earthquake:'新耐震',offers:13,img:'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80'},
{id:11,name:'調布市仙川町 売地',area:'調布市',address:'東京都調布市仙川町',type:'土地',price:'5,950万円',status:'入札予定',time:'開始まで9日',size:'土地 125.60㎡',built:'—',prefecture:'東京都',line:'京王線',station:'仙川駅',walk:10,landArea:125.60,earthquake:'対象外',offers:4,img:'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=900&q=80'},
{id:12,name:'町田市原町田 一棟マンション',area:'町田市',address:'東京都町田市原町田',type:'1棟マンション',price:'1億3,800万円',status:'終了',time:'落札済み',size:'建物 302.14㎡',built:'1988年6月',prefecture:'東京都',line:'小田急小田原線',station:'町田駅',walk:7,landArea:178.40,earthquake:'新耐震',offers:16,img:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80'},
{id:13,name:'八王子市みなみ野 戸建て',area:'八王子市',address:'東京都八王子市みなみ野',type:'戸建て',price:'3,980万円',status:'オークション中',time:'残り8時間20分',size:'建物 110.42㎡',built:'2004年9月',prefecture:'東京都',line:'JR横浜線',station:'八王子みなみ野駅',walk:12,landArea:165.20,earthquake:'新耐震',offers:15,img:'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=900&q=80'},
{id:14,name:'国分寺市本町 旧耐震マンション 303号室',area:'国分寺市',address:'東京都国分寺市本町',type:'区分マンション',price:'2,980万円',status:'終了',time:'受付終了',size:'専有 57.82㎡',built:'1978年11月',prefecture:'東京都',line:'JR中央線',station:'国分寺駅',walk:4,landArea:0,earthquake:'旧耐震',offers:9,img:'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80'},
{id:15,name:'西多摩郡瑞穂町 箱根ケ崎 売地',area:'瑞穂町',address:'東京都西多摩郡瑞穂町箱根ケ崎',type:'土地',price:'2,450万円',status:'終了',time:'落札済み',size:'土地 218.50㎡',built:'—',prefecture:'東京都',line:'JR八高線',station:'箱根ケ崎駅',walk:15,landArea:218.50,earthquake:'対象外',offers:5,img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80'}];
const tokyoWards=['千代田区','中央区','港区','新宿区','文京区','台東区','墨田区','江東区','品川区','目黒区','大田区','世田谷区','渋谷区','中野区','杉並区','豊島区','北区','荒川区','板橋区','練馬区','足立区','葛飾区','江戸川区'];
const tamaAreas=['八王子市','立川市','武蔵野市','三鷹市','青梅市','府中市','昭島市','調布市','町田市','小金井市','小平市','日野市','東村山市','国分寺市','国立市','福生市','狛江市','東大和市','清瀬市','東久留米市','武蔵村山市','多摩市','稲城市','羽村市','あきる野市','西東京市','瑞穂町','日の出町','檜原村','奥多摩町'];
const lineGroups={JR:['JR山手線','JR京浜東北線','JR中央線','JR総武線','JR埼京線','JR湘南新宿ライン','JR常磐線','JR京葉線','JR横浜線','JR南武線','JR青梅線','JR五日市線','JR八高線'],東京メトロ:['東京メトロ銀座線','東京メトロ丸ノ内線','東京メトロ日比谷線','東京メトロ東西線','東京メトロ千代田線','東京メトロ有楽町線','東京メトロ半蔵門線','東京メトロ南北線','東京メトロ副都心線'],都営地下鉄:['都営浅草線','都営三田線','都営新宿線','都営大江戸線'],私鉄:['東急東横線','東急田園都市線','東急大井町線','東急池上線','東急目黒線','京王線','京王井の頭線','小田急小田原線','西武新宿線','西武池袋線','東武東上線','東武伊勢崎線','京成本線','京急本線','つくばエクスプレス','ゆりかもめ','多摩モノレール']};
function checkboxGroup(name,values){return values.map(x=>`<label><input type="checkbox" name="${name}" value="${x}"> ${x}</label>`).join('')}

const app=document.querySelector('#app');
const favorites=new Set([1,7,9]);
function nav(){document.querySelector('#main-nav').innerHTML='<button data-screen="home">物件一覧</button><button data-screen="search">物件を探す</button><button data-screen="mypage">マイページ</button><button data-screen="notices">お知らせ</button>';}
function propertyCard(p){const saved=favorites.has(p.id);return `<article class="listing-card"><div class="listing-image" style="background-image:url('${p.img}')"><span class="badge">${p.status}</span><button class="favorite-btn ${saved?'saved':''}" data-favorite="${p.id}" aria-label="${saved?'お気に入りから削除':'お気に入りに登録'}">${saved?'♥':'♡'}</button></div><div class="listing-main"><div class="listing-kicker">${p.type}｜${p.address}</div><h3>${p.name}</h3>${p.type!=='土地'?`<span class="earthquake-tag ${p.earthquake==='旧耐震'?'old':''}">${p.earthquake}</span>`:''}<dl class="listing-facts"><div><dt>価格</dt><dd>${p.price}</dd></div><div><dt>面積</dt><dd>${p.size}</dd></div><div><dt>築年月</dt><dd>${p.built}</dd></div></dl></div><div class="listing-action"><strong>${p.time}</strong><span>オファー済み ${p.offers}件</span><button class="btn" data-detail="${p.id}">物件詳細を見る</button></div></article>`}
function statusSections(items){return ['入札予定','オークション中','終了'].map(status=>{const matches=items.filter(p=>p.status===status);return `<section class="status-section" data-status-section="${status}"><div class="status-heading"><div><span class="status-dot"></span><h2>${status}</h2><b>${matches.length}件</b></div><p>${status==='入札予定'?'資料を確認し、オファーや資金準備を進められる物件です。':status==='オークション中'?'現在入札を受け付けている物件です。':'オークションの受付を終了した物件です。'}</p></div><div class="listing-stack">${matches.map(propertyCard).join('')}</div></section>`}).join('')}
function home(){app.innerHTML=`<section class="buyer-hero"><div class="buyer-hero-card"><div class="eyebrow">REAL ESTATE AUCTION</div><h1>不動産オークションの<br><strong>ITTO</strong></h1><p>住まいも、土地も。豊富な物件から希望の条件で探して、納得のいく購入へ。</p><div class="hero-actions"><button class="btn" data-screen="search">物件を探す</button><button class="beginner-btn" data-screen="guide"><span>🔰</span> はじめての方へ</button><span>掲載物件 ${properties.length}件</span></div></div></section><div class="catalog-wrap"><div class="catalog-heading"><div><span class="eyebrow">PROPERTY LIST</span><h2>販売中の物件</h2></div></div><div class="status-filter"><strong>表示するカテゴリー</strong>${['入札予定','オークション中','終了'].map(x=>`<label><input type="checkbox" name="status" value="${x}" checked> ${x}</label>`).join('')}<span id="home-result">${properties.length}件</span></div><div>${statusSections(properties)}</div></div>`}
function search(){app.innerHTML=`<div class="page-title"><div class="breadcrumb">ホーム / 物件を探す</div><h1>物件検索</h1><p class="muted">場所・物件種別・広さ・駅からの距離を組み合わせて絞り込めます。</p></div><div class="search-layout"><aside class="search-panel"><form id="search-form"><fieldset><legend>場所から探す</legend><div class="search-mode-tabs"><button type="button" class="active" data-search-mode="prefecture">都道府県から探す</button><button type="button" data-search-mode="line">沿線から探す</button></div><div data-mode-panel="prefecture"><p class="filter-note">都道府県</p><label><input type="checkbox" name="prefecture" value="東京都"> 東京都</label><details class="filter-dropdown"><summary>東京23区から選ぶ</summary><div class="filter-checks compact">${checkboxGroup('area',tokyoWards)}</div></details><details class="filter-dropdown"><summary>多摩地区から選ぶ</summary><div class="filter-checks compact">${checkboxGroup('area',tamaAreas)}</div></details></div><div data-mode-panel="line" hidden>${Object.entries(lineGroups).map(([group,lines])=>`<details class="filter-dropdown"><summary>${group}から選ぶ</summary><div class="filter-checks">${checkboxGroup('line',lines)}</div></details>`).join('')}</div></fieldset><fieldset><legend>物件種別</legend><div class="filter-checks">${checkboxGroup('type',['土地','戸建て','区分マンション','1棟アパート','1棟マンション'])}</div></fieldset><fieldset><legend>追加条件</legend><label class="select-filter">土地面積<select name="land-area"><option value="0">指定なし</option>${[50,75,100,150,200,250,300,350,400,450,500].map(x=>`<option value="${x}">${x}㎡以上</option>`).join('')}</select></label><label class="select-filter">駅からの徒歩分数<select name="walk"><option value="0">指定なし</option>${Array.from({length:20},(_,i)=>i+1).map(x=>`<option value="${x}">${x}分以内</option>`).join('')}</select></label></fieldset><div class="search-buttons"><button class="btn" type="submit">この条件で検索</button><button class="text-button" type="reset">条件をクリア</button></div></form></aside><section class="search-results"><div class="result-head"><h2>検索結果</h2><strong id="result-count">${properties.length}件</strong></div><div id="search-list" class="listing-stack">${properties.map(propertyCard).join('')}</div></section></div>`}
function shell(title,sub,content){app.innerHTML=`<div class="page-title"><div class="breadcrumb">ホーム / ${title}</div><h1>${title}</h1><div class="muted">${sub}</div></div>${content}`}
function mypage(){const stats=[['お気に入り',`${favorites.size}件`],['提出済みオファー','1件'],['参加中の入札','1件'],['未確認のお知らせ','2件']];shell('マイページ','検討中の物件や、参加している取引の状況を確認できます。',`<div class="dashboard"><div class="stat-grid">${stats.map(x=>`<div class="card stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="layout"><section class="panel"><div class="panel-head"><h2>最近確認した物件</h2></div><div class="panel-body listing-stack">${properties.slice(0,2).map(propertyCard).join('')}</div></section><aside class="panel"><div class="panel-head"><h2>お知らせ</h2></div><div class="panel-body"><div class="notice">オークションの開始時刻が近づいています。<br><small>本日 10:30</small></div><div class="notice">提出したオファーを受け付けました。<br><small>昨日 16:15</small></div></div></aside></div></div>`)}
function detail(id){const p=properties.find(x=>x.id===Number(id))||properties[0],action=p.status==='入札予定'?'オファーする':p.status==='オークション中'?'入札する':'受付終了';shell(p.name,'物件詳細・資料閲覧',`<div class="dashboard"><div class="steps">${['入札予定','オークション','落札','優先交渉','契約・決済','成約'].map((x,i)=>`<div class="step ${i<1?'done':i===1?'active':''}"><span></span>${x}</div>`).join('')}</div><div class="layout"><div><div class="property-image" style="height:390px;background-image:url('${p.img}')"></div><section class="panel"><div class="panel-head"><h2>物件概要</h2></div><div class="panel-body"><table class="data-table"><tr><th>所在地</th><td>${p.address}</td><th>物件種別</th><td>${p.type}</td></tr><tr><th>販売価格</th><td>${p.price}</td><th>築年月</th><td>${p.built}</td></tr><tr><th>面積</th><td>${p.size}</td><th>引渡し</th><td>相談</td></tr><tr><th>最寄駅</th><td>${p.station} 徒歩${p.walk}分</td><th>耐震区分</th><td>${p.earthquake}</td></tr></table></div></section></div><aside><div class="auction"><span class="badge">${p.status}</span><div class="price">${p.price}</div><small>販売価格</small><hr><p><strong>${p.time}</strong></p><button class="btn gold" ${p.status==='終了'?'disabled':`data-offer="${p.id}"`}>${action}</button></div></aside></div></div>`)}
function offerPage(id){const p=properties.find(x=>x.id===Number(id))||properties[0],isBid=p.status==='オークション中',label=isBid?'入札':'オファー';shell(`${label}内容の入力`,`${p.name}｜入力内容は見本画面では送信されません。`,`<div class="dashboard offer-layout"><section class="panel"><div class="panel-head"><h2>${p.name}</h2><span class="badge">${p.status}</span></div><div class="panel-body"><form id="offer-form" class="offer-form"><input type="hidden" name="property-id" value="${p.id}"><div class="offer-summary"><span>${isBid?'現在価格':'販売価格'}</span><strong>${p.price}</strong></div><label class="offer-field"><span>${label}金額</span><div class="money-input"><input name="amount" inputmode="numeric" required placeholder="例：75000000"><b>円</b></div><small>半角数字で入力してください。</small></label><label class="offer-field"><span>オファーコメント</span><textarea name="comment" rows="5" placeholder="購入希望条件や資金計画などを入力してください。"></textarea><small>売主が条件を確認するための補足です。</small></label><div class="notice">${isBid?'入札後の取り消しはできません。':'オファーは購入意向の確認であり、この時点で売買は成立しません。'}</div><button class="btn offer-submit" type="submit">${label}内容を確認する</button></form></div></section><aside class="panel"><div class="panel-head"><h2>入力前の確認</h2></div><div class="panel-body"><ol class="check-list"><li>物件資料を確認する</li><li>金額と購入条件を入力する</li><li>確認画面で内容を確定する</li></ol><p class="muted">この見本画面では実際の送信・入札は行われません。</p></div></aside></div>`)}
function guide(){shell('はじめての方へ','ITTO不動産オークションへの参加方法をご案内します。',`<div class="dashboard"><section class="guide-intro"><span class="guide-mark">🔰</span><div><div class="eyebrow">AUCTION GUIDE</div><h2>ITTOオークションは、4つのステップで参加できます</h2><p>気になる物件探しからオファー・入札、その後の優先交渉まで、画面に沿って進められます。</p></div></section><div class="guide-steps">${[['1','物件を探す','地域・沿線・物件種別など、希望条件から物件を探します。'],['2','資料を確認する','物件詳細、販売条件、公開資料、オークション日程を確認します。'],['3','オファー・入札する','金額と購入希望条件を入力します。オファー時点では売買は成立しません。'],['4','優先交渉へ進む','オークション後、売主から選ばれた買主が優先交渉へ進みます。']].map(x=>`<article><b>STEP ${x[0]}</b><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div><div class="guide-note"><h2>落札と成約は別です</h2><p>最高額の入札者が決まる「落札」の後、売主が価格と条件を比較して優先交渉する買主を選びます。契約・決済が完了した時点で「成約」となります。</p><button class="btn" data-screen="search">物件を探してみる</button></div></div>`)}
function notices(){shell('お知らせ一覧','オークション開始やオファーに関する連絡を確認できます。','<div class="dashboard"><section class="panel"><div class="panel-body"><div class="notice">THE RESIDENCE 白金台のオークション終了が近づいています。<br><small>本日 10:30</small></div><div class="notice">代官山 TERRACEへのオファーを受け付けました。<br><small>昨日 16:15</small></div></div></section></div>')}
function applySearch(){const selected=name=>[...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value),types=selected('type'),areas=selected('area'),prefectures=selected('prefecture'),lines=selected('line'),landMin=Number(document.querySelector('[name="land-area"]')?.value||0),walkMax=Number(document.querySelector('[name="walk"]')?.value||0),found=properties.filter(p=>(!types.length||types.includes(p.type))&&(!areas.length||areas.includes(p.area))&&(!prefectures.length||prefectures.includes(p.prefecture))&&(!lines.length||lines.includes(p.line))&&(!landMin||p.landArea>=landMin)&&(!walkMax||p.walk<=walkMax));document.querySelector('#result-count').textContent=`${found.length}件`;document.querySelector('#search-list').innerHTML=found.length?found.map(propertyCard).join(''):'<div class="empty-result"><strong>該当する物件がありません</strong><p>条件を減らして、もう一度お試しください。</p></div>'}
document.addEventListener('change',e=>{if(e.target.matches('input[name="status"]')){const checked=[...document.querySelectorAll('input[name="status"]:checked')].map(x=>x.value);document.querySelectorAll('[data-status-section]').forEach(x=>x.hidden=!checked.includes(x.dataset.statusSection));document.querySelector('#home-result').textContent=`${properties.filter(p=>checked.includes(p.status)).length}件`}});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='search-form')return applySearch();if(e.target.id==='offer-form')return toast('入力内容を確認しました（見本画面）')});document.addEventListener('reset',e=>{if(e.target.id==='search-form')setTimeout(applySearch)});
document.addEventListener('click',e=>{const mode=e.target.closest('[data-search-mode]')?.dataset.searchMode;if(mode){document.querySelectorAll('[data-search-mode]').forEach(x=>x.classList.toggle('active',x.dataset.searchMode===mode));document.querySelectorAll('[data-mode-panel]').forEach(x=>x.hidden=x.dataset.modePanel!==mode);return}const screen=e.target.closest('[data-screen]')?.dataset.screen;if(screen){({home,search,mypage,notices,guide}[screen]||home)();return}const favorite=e.target.closest('[data-favorite]')?.dataset.favorite;if(favorite){const id=Number(favorite);favorites.has(id)?favorites.delete(id):favorites.add(id);e.target.closest('[data-favorite]').classList.toggle('saved',favorites.has(id));e.target.closest('[data-favorite]').textContent=favorites.has(id)?'♥':'♡';return}const offer=e.target.closest('[data-offer]')?.dataset.offer;if(offer)return offerPage(offer);const id=e.target.closest('[data-detail]')?.dataset.detail;if(id)return detail(id);if(e.target.closest('[data-action="home"]'))return home();if(e.target.closest('[data-demo]'))toast('見本画面のため、実際の処理は行われません。')});
function toast(msg){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2800)}nav();home();
