const properties=[
{id:1,name:'白金台 パークレジデンス 603号室',area:'港区',address:'東京都港区白金台',type:'区分マンション',price:'1億2,800万円',status:'オークション中',time:'残り18時間42分',size:'専有 72.18㎡',built:'2018年3月',prefecture:'東京都',line:'都営三田線',station:'白金台駅',walk:4,landArea:0,earthquake:'新耐震',offers:12,img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80'},
{id:2,name:'渋谷区代官山町 売地',area:'渋谷区',address:'東京都渋谷区代官山町',type:'土地',price:'9,480万円',status:'入札予定',time:'開始まで12日',size:'土地 82.44㎡',built:'—',prefecture:'東京都',line:'東急東横線',station:'代官山駅',walk:7,landArea:82.44,earthquake:'対象外',offers:8,img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80'},
{id:3,name:'世田谷区深沢 戸建て',area:'世田谷区',address:'東京都世田谷区深沢',type:'戸建て',price:'7,980万円',status:'入札予定',time:'オファー受付中',size:'建物 104.26㎡',built:'2021年6月',prefecture:'東京都',line:'東急大井町線',station:'尾山台駅',walk:14,landArea:96.18,earthquake:'新耐震',offers:5,img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80'},
{id:4,name:'目黒区中央町 一棟アパート',area:'目黒区',address:'東京都目黒区中央町',type:'1棟アパート',price:'1億4,500万円',status:'オークション中',time:'残り2日6時間',size:'建物 186.30㎡',built:'1979年8月',prefecture:'東京都',line:'東急東横線',station:'学芸大学駅',walk:11,landArea:102.60,earthquake:'旧耐震',offers:9,img:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=80'},
{id:5,name:'吉祥寺北町 売地',area:'武蔵野市',address:'東京都武蔵野市吉祥寺北町',type:'土地',price:'6,250万円',status:'終了',time:'受付終了',size:'土地 116.82㎡',built:'—',prefecture:'東京都',line:'JR中央線',station:'吉祥寺駅',walk:18,landArea:116.82,earthquake:'対象外',offers:14,img:'https://images.unsplash.com/photo-1523413651479-597eb2da0ad6?auto=format&fit=crop&w=900&q=80'},
{id:6,name:'横浜ベイサイド 408号室',area:'横浜市',address:'神奈川県横浜市中区山下町',type:'区分マンション',price:'2,850万円',status:'終了',time:'落札済み',size:'専有 61.45㎡',built:'2019年2月',prefecture:'神奈川県',line:'みなとみらい線',station:'元町・中華街駅',walk:6,landArea:0,earthquake:'新耐震',offers:18,img:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80'}];
const app=document.querySelector('#app');
function nav(){document.querySelector('#main-nav').innerHTML='<button data-screen="home">物件一覧</button><button data-screen="search">物件を探す</button><button data-screen="mypage">マイページ</button><button data-screen="notices">お知らせ</button>';}
function propertyCard(p){return `<article class="listing-card"><div class="listing-image" style="background-image:url('${p.img}')"><span class="badge">${p.status}</span></div><div class="listing-main"><div class="listing-kicker">${p.type}｜${p.address}</div><h3>${p.name}</h3>${p.type!=='土地'?`<span class="earthquake-tag ${p.earthquake==='旧耐震'?'old':''}">${p.earthquake}</span>`:''}<dl class="listing-facts"><div><dt>価格</dt><dd>${p.price}</dd></div><div><dt>面積</dt><dd>${p.size}</dd></div><div><dt>築年月</dt><dd>${p.built}</dd></div></dl></div><div class="listing-action"><strong>${p.time}</strong><span>オファー済み ${p.offers}件</span><button class="btn" data-detail="${p.id}">物件詳細を見る</button></div></article>`}
function statusSections(items){return ['入札予定','オークション中','終了'].map(status=>{const matches=items.filter(p=>p.status===status);return `<section class="status-section" data-status-section="${status}"><div class="status-heading"><div><span class="status-dot"></span><h2>${status}</h2><b>${matches.length}件</b></div><p>${status==='入札予定'?'資料を確認し、オファーや資金準備を進められる物件です。':status==='オークション中'?'現在入札を受け付けている物件です。':'オークションの受付を終了した物件です。'}</p></div><div class="listing-stack">${matches.map(propertyCard).join('')}</div></section>`}).join('')}
function home(){app.innerHTML=`<section class="buyer-hero"><div><div class="eyebrow">ITTO PROPERTY AUCTION</div><h1>納得できる住まいと土地を、<br>確かな情報から。</h1><p>入札前の検討からオークション終了まで、販売状況ごとに物件を探せます。</p><button class="btn gold" data-screen="search">条件を指定して探す</button></div></section><div class="catalog-wrap"><div class="catalog-heading"><div><span class="eyebrow">PROPERTY LIST</span><h2>販売中の物件</h2></div></div><div class="status-filter"><strong>表示するカテゴリー</strong>${['入札予定','オークション中','終了'].map(x=>`<label><input type="checkbox" name="status" value="${x}" checked> ${x}</label>`).join('')}<span id="home-result">6件</span></div><div>${statusSections(properties)}</div></div>`}
function search(){app.innerHTML=`<div class="page-title"><div class="breadcrumb">ホーム / 物件を探す</div><h1>物件検索</h1><p class="muted">場所・物件種別・広さ・駅からの距離を組み合わせて絞り込めます。</p></div><div class="search-layout"><aside class="search-panel"><form id="search-form"><fieldset><legend>場所から探す</legend><div class="search-mode-tabs"><button type="button" class="active" data-search-mode="prefecture">都道府県から探す</button><button type="button" data-search-mode="line">沿線から探す</button></div><div data-mode-panel="prefecture"><p class="filter-note">都道府県</p><div class="filter-checks compact">${['東京都','神奈川県'].map(x=>`<label><input type="checkbox" name="prefecture" value="${x}"> ${x}</label>`).join('')}</div><p class="filter-note">市区町村</p><div class="filter-checks compact">${['港区','渋谷区','世田谷区','目黒区','武蔵野市','横浜市'].map(x=>`<label><input type="checkbox" name="area" value="${x}"> ${x}</label>`).join('')}</div></div><div data-mode-panel="line" hidden><p class="filter-note">沿線</p><div class="filter-checks">${['JR中央線','東急東横線','東急大井町線','都営三田線','みなとみらい線'].map(x=>`<label><input type="checkbox" name="line" value="${x}"> ${x}</label>`).join('')}</div></div></fieldset><fieldset><legend>物件種別</legend><div class="filter-checks">${['土地','戸建て','区分マンション','1棟アパート','1棟マンション'].map(x=>`<label><input type="checkbox" name="type" value="${x}"> ${x}</label>`).join('')}</div></fieldset><fieldset><legend>追加条件</legend><label class="select-filter">土地面積<select name="land-area"><option value="0">指定なし</option>${[50,75,100,150,200,250,300,350,400,450,500].map(x=>`<option value="${x}">${x}㎡以上</option>`).join('')}</select></label><label class="select-filter">駅からの徒歩分数<select name="walk"><option value="0">指定なし</option>${Array.from({length:20},(_,i)=>i+1).map(x=>`<option value="${x}">${x}分以内</option>`).join('')}</select></label></fieldset><div class="search-buttons"><button class="btn" type="submit">この条件で検索</button><button class="text-button" type="reset">条件をクリア</button></div></form></aside><section class="search-results"><div class="result-head"><h2>検索結果</h2><strong id="result-count">6件</strong></div><div id="search-list" class="listing-stack">${properties.map(propertyCard).join('')}</div></section></div>`}
function shell(title,sub,content){app.innerHTML=`<div class="page-title"><div class="breadcrumb">ホーム / ${title}</div><h1>${title}</h1><div class="muted">${sub}</div></div>${content}`}
function mypage(){const stats=[['検討中','3件'],['提出済みオファー','1件'],['参加中の入札','1件'],['未確認のお知らせ','2件']];shell('マイページ','検討中の物件や、参加している取引の状況を確認できます。',`<div class="dashboard"><div class="stat-grid">${stats.map(x=>`<div class="card stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="layout"><section class="panel"><div class="panel-head"><h2>最近確認した物件</h2></div><div class="panel-body listing-stack">${properties.slice(0,2).map(propertyCard).join('')}</div></section><aside class="panel"><div class="panel-head"><h2>お知らせ</h2></div><div class="panel-body"><div class="notice">オークションの開始時刻が近づいています。<br><small>本日 10:30</small></div><div class="notice">提出したオファーを受け付けました。<br><small>昨日 16:15</small></div></div></aside></div></div>`)}
function detail(id){const p=properties.find(x=>x.id===Number(id))||properties[0];shell(p.name,'物件詳細・資料閲覧',`<div class="dashboard"><div class="steps">${['入札予定','オークション','落札','優先交渉','契約・決済','成約'].map((x,i)=>`<div class="step ${i<1?'done':i===1?'active':''}"><span></span>${x}</div>`).join('')}</div><div class="layout"><div><div class="property-image" style="height:390px;background-image:url('${p.img}')"></div><section class="panel"><div class="panel-head"><h2>物件概要</h2></div><div class="panel-body"><table class="data-table"><tr><th>所在地</th><td>${p.address}</td><th>物件種別</th><td>${p.type}</td></tr><tr><th>販売価格</th><td>${p.price}</td><th>築年月</th><td>${p.built}</td></tr><tr><th>面積</th><td>${p.size}</td><th>引渡し</th><td>相談</td></tr></table></div></section></div><aside><div class="auction"><span class="badge">${p.status}</span><div class="price">${p.price}</div><small>販売価格</small><hr><p><strong>${p.time}</strong></p><button class="btn gold" data-demo>オファー・入札へ進む</button></div></aside></div></div>`)}
function notices(){shell('お知らせ一覧','オークション開始やオファーに関する連絡を確認できます。','<div class="dashboard"><section class="panel"><div class="panel-body"><div class="notice">THE RESIDENCE 白金台のオークション終了が近づいています。<br><small>本日 10:30</small></div><div class="notice">代官山 TERRACEへのオファーを受け付けました。<br><small>昨日 16:15</small></div></div></section></div>')}
function applySearch(){const selected=name=>[...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value),types=selected('type'),areas=selected('area'),prefectures=selected('prefecture'),lines=selected('line'),landMin=Number(document.querySelector('[name="land-area"]')?.value||0),walkMax=Number(document.querySelector('[name="walk"]')?.value||0),found=properties.filter(p=>(!types.length||types.includes(p.type))&&(!areas.length||areas.includes(p.area))&&(!prefectures.length||prefectures.includes(p.prefecture))&&(!lines.length||lines.includes(p.line))&&(!landMin||p.landArea>=landMin)&&(!walkMax||p.walk<=walkMax));document.querySelector('#result-count').textContent=`${found.length}件`;document.querySelector('#search-list').innerHTML=found.length?found.map(propertyCard).join(''):'<div class="empty-result"><strong>該当する物件がありません</strong><p>条件を減らして、もう一度お試しください。</p></div>'}
document.addEventListener('change',e=>{if(e.target.matches('input[name="status"]')){const checked=[...document.querySelectorAll('input[name="status"]:checked')].map(x=>x.value);document.querySelectorAll('[data-status-section]').forEach(x=>x.hidden=!checked.includes(x.dataset.statusSection));document.querySelector('#home-result').textContent=`${properties.filter(p=>checked.includes(p.status)).length}件`}});
document.addEventListener('submit',e=>{if(e.target.id==='search-form'){e.preventDefault();applySearch()}});document.addEventListener('reset',e=>{if(e.target.id==='search-form')setTimeout(applySearch)});
document.addEventListener('click',e=>{const mode=e.target.closest('[data-search-mode]')?.dataset.searchMode;if(mode){document.querySelectorAll('[data-search-mode]').forEach(x=>x.classList.toggle('active',x.dataset.searchMode===mode));document.querySelectorAll('[data-mode-panel]').forEach(x=>x.hidden=x.dataset.modePanel!==mode);return}const screen=e.target.closest('[data-screen]')?.dataset.screen;if(screen){({home,search,mypage,notices}[screen]||home)();return}const id=e.target.closest('[data-detail]')?.dataset.detail;if(id)return detail(id);if(e.target.closest('[data-action="home"]'))return home();if(e.target.closest('[data-demo]'))toast('見本画面のため、実際の処理は行われません。')});
function toast(msg){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2800)}nav();home();
